name: pull_request

on:
  pull_request:
    types: [synchronize, reopened]
    branches:
      - master
      - "release-[0-9]+.*"
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  package:
    name: package and upload release assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: build
        env:
          CGO_ENABLED: 0
        run: |
          make build-dev
          ls -lh k6*